// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Interfaz.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20220314215701_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

            modelBuilder.Entity("Caja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Arandanos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ciruelas")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("Manies")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Pasas")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Peso")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Pistachos")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Cajas");
                });

            modelBuilder.Entity("Fundita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Arandanos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ciruelas")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("Manies")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Pasas")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Peso")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Pistachos")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Funditas");
                });

            modelBuilder.Entity("Inventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Inventario");
                });
#pragma warning restore 612, 618
        }
    }
}
